// Reverts tgs paramedic access
/datum/id_trim/job/paramedic
	minimal_access = list(
		ACCESS_BIT_DEN,
		ACCESS_CARGO,
		ACCESS_CONSTRUCTION,
		ACCESS_HYDROPONICS,
		ACCESS_MAINT_TUNNELS,
		ACCESS_MECH_MEDICAL,
		ACCESS_MEDICAL,
		ACCESS_MINERAL_STOREROOM,
		ACCESS_MINING,
		ACCESS_MINING_STATION,
		ACCESS_MORGUE,
		ACCESS_SCIENCE,
		ACCESS_SERVICE,
		)

	extra_access = list(
		ACCESS_SURGERY,
		ACCESS_VIROLOGY,
		ACCESS_PHARMACY,
		)
