// see "code\__DEFINES\~~bubber_defines\jobs.dm"
#define JOB_UNAVAILABLE_WHITELISTED (JOB_UNAVAILABLE_FLAVOUR_SILICON + 1)
/*#define WHITELIST_ONLY_JOBS list( \
			JOB_CAPTAIN, \
			JOB_HEAD_OF_PERSONNEL, \
			JOB_HEAD_OF_SECURITY, \
			JOB_RESEARCH_DIRECTOR, \
			JOB_CHIEF_ENGINEER, \
			JOB_CHIEF_MEDICAL_OFFICER, \
			JOB_BRIDGE_ASSISTANT, \
			JOB_VETERAN_ADVISOR, \
			JOB_BLUESHIELD, \
			JOB_NT_REP, \
)*/
