/datum/centcom_announcer/dagoth_ur // The Seventh Rizz Unmourned
	welcome_sounds = list('modular_zzplurt/sound/announcer/dagoth/welcomes/01.ogg',
		'modular_zzplurt/sound/announcer/dagoth/welcomes/02.ogg',
		'modular_zzplurt/sound/announcer/dagoth/welcomes/03.ogg',
		'modular_zzplurt/sound/announcer/dagoth/welcomes/04.ogg',
		'modular_zzplurt/sound/announcer/dagoth/welcomes/05.ogg',
		'modular_zzplurt/sound/announcer/dagoth/welcomes/06.ogg',
		'modular_zzplurt/sound/announcer/dagoth/welcomes/07.ogg')

	alert_sounds = list('modular_zzplurt/sound/announcer/dagoth/alerts/01.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/02.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/03.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/04.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/05.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/06.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/07.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/08.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/09.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/10.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/11.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/12.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/13.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/14.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/15.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/16.ogg',
		'modular_zzplurt/sound/announcer/dagoth/alerts/17.ogg')

	command_report_sounds = list('modular_zzplurt/sound/announcer/dagoth/commandreport/01.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/02.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/03.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/04.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/05.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/06.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/07.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/08.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/09.ogg',
		'modular_zzplurt/sound/announcer/dagoth/commandreport/10.ogg')

	event_sounds = list(
		ANNOUNCER_AIMALF = 'modular_zzplurt/sound/announcer/dagoth/aimalf.ogg',
		ANNOUNCER_ALIENS = 'modular_zzplurt/sound/announcer/dagoth/lifesigns.ogg',
		ANNOUNCER_ANIMES = 'modular_zzplurt/sound/announcer/dagoth/animes.ogg',
		ANNOUNCER_INTERCEPT = 'modular_zzplurt/sound/announcer/dagoth/alert2.ogg',
		ANNOUNCER_GRANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/gravanomalies.ogg',
		ANNOUNCER_IONSTORM = 'modular_zzplurt/sound/announcer/dagoth/Ionstorm.ogg',
		ANNOUNCER_METEORS = 'modular_zzplurt/sound/announcer/dagoth/Meteors.ogg',
		ANNOUNCER_OUTBREAK5 = 'modular_zzplurt/sound/announcer/dagoth/outbreak5.ogg',
		ANNOUNCER_OUTBREAK6 = 'modular_zzplurt/sound/announcer/dagoth/alert3.ogg',
		ANNOUNCER_OUTBREAK7 = 'modular_zzplurt/sound/announcer/dagoth/outbreak7.ogg',
		ANNOUNCER_POWEROFF = 'modular_zzplurt/sound/announcer/dagoth/poweroffALT.ogg',
		ANNOUNCER_POWERON = 'modular_zzplurt/sound/announcer/dagoth/poweron.ogg',
		ANNOUNCER_RADIATION = 'modular_zzplurt/sound/announcer/dagoth/radiation.ogg',
		ANNOUNCER_RADIATIONPASSED = 'modular_zzplurt/sound/announcer/dagoth/radpassed.ogg',
		ANNOUNCER_SHUTTLECALLED = 'modular_zzplurt/sound/announcer/dagoth/crew_shuttle_called.ogg',
		ANNOUNCER_SHUTTLEDOCK = 'modular_zzplurt/sound/announcer/dagoth/crew_shuttled_docked.ogg',
		ANNOUNCER_SHUTTLERECALLED = 'modular_zzplurt/sound/announcer/dagoth/crew_shuttle_recalled.ogg',
		ANNOUNCER_SHUTTLELEFT = 'modular_zzplurt/sound/announcer/dagoth/crew_shuttle_left.ogg',
		ANNOUNCER_ANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/anomaly.ogg',
		ANNOUNCER_GRAVANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/gravanomalies.ogg',
		ANNOUNCER_SPANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/wormholes.ogg',
		//ANNOUNCER_VORTEXANOMALIES = 'modular_skyrat/modules/alerts/sound/alerts/vortex.ogg',
		ANNOUNCER_MASSIVEBSPACEANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/bluespace_anomalies.ogg',
		ANNOUNCER_TRANSLOCATION = 'modular_zzplurt/sound/announcer/dagoth/translocation.ogg',
		ANNOUNCER_FLUXANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/Flux.ogg',
		ANNOUNCER_PYROANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/pyr_anomalies.ogg',
		ANNOUNCER_CARP = 'modular_zzplurt/sound/announcer/dagoth/carps.ogg',
		ANNOUNCER_BLUESPACEARTY = 'modular_zzplurt/sound/announcer/dagoth/artillery.ogg',
		ANNOUNCER_CAPTAIN = 'modular_zzplurt/sound/announcer/dagoth/announce.ogg',
		ANNOUNCER_GRAVANOMALIES = 'modular_zzplurt/sound/announcer/dagoth/gravanomalies.ogg',
		ANNOUNCER_GRAVGENOFF = 'modular_zzplurt/sound/announcer/dagoth/gravityoff.ogg',
		ANNOUNCER_GRAVGENON = 'modular_zzplurt/sound/announcer/dagoth/gravityon.ogg',
		ANNOUNCER_GREYTIDE = 'modular_zzplurt/sound/announcer/dagoth/greytide.ogg',
		ANNOUNCER_COMMSBLACKOUT = 'modular_zzplurt/sound/announcer/dagoth/commsblackout.ogg',
		ANNOUNCER_ELECTRICALSTORM = 'modular_zzplurt/sound/announcer/dagoth/estorm.ogg',
		ANNOUNCER_BRANDINTELLIGENCE = 'modular_zzplurt/sound/announcer/dagoth/rampant_brand_int.ogg',
		//ANNOUNCER_SPOOKY = 'modular_skyrat/modules/alerts/sound/misc/admin_horror_music.ogg',
		ANNOUNCER_ERTYES = 'modular_zzplurt/sound/announcer/dagoth/yesert.ogg',
		//ANNOUNCER_ERTNO = 'modular_zzplurt/sound/announcer/dagoth/ertno.ogg', //what
		//ANNOUNCER_MUTANTS = 'modular_skyrat/modules/alerts/sound/alerts/hazdet.ogg',
		ANNOUNCER_ICARUS = 'modular_skyrat/modules/assault_operatives/sound/icarus_alarm.ogg',
		ANNOUNCER_NRI_RAIDERS = 'modular_skyrat/modules/encounters/sounds/morse.ogg',
		ANNOUNCER_DEPARTMENTAL = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_SHUTTLE = 'modular_skyrat/modules/alerts/sound/alerts/alert3.ogg',
		ANNOUNCER_AURORA_CAELUS = 'modular_zzplurt/sound/announcer/dagoth/auroracaelus.ogg',
		ANNOUNCER_BUREAUCRATIC_ERROR = 'modular_zzplurt/sound/announcer/dagoth/bureaucraticerror.ogg',
		ANNOUNCER_MARKET_CRASH = 'modular_zzplurt/sound/announcer/dagoth/marketcrash.ogg',
		ANNOUNCER_MOUSE_MIGRATION = 'modular_zzplurt/sound/announcer/dagoth/mouse_migration.ogg',
		ANNOUNCER_SCRUBBER_OVERFLOW = 'modular_zzplurt/sound/announcer/dagoth/scrubberoverflow.ogg',
		ANNOUNCER_SHUTTLE_INSURANCE = 'modular_zzplurt/sound/announcer/dagoth/shuttleinsurance.ogg',
		ANNOUNCER_SUPERMATTER_SURGE = 'modular_zzplurt/sound/announcer/dagoth/supermatter_surge.ogg',
		ANNOUNCER_WISDOM_COW = 'modular_zzplurt/sound/announcer/dagoth/wisdom_cow.ogg',
		ANNOUNCER_IMMOVABLE_ROD = 'modular_zzplurt/sound/announcer/dagoth/immovablerod.ogg',
		ANNOUNCER_SCRAMBLER_ANOMALY = 'modular_zzplurt/sound/announcer/dagoth/scrambleranom.ogg'
	)

	//custom_alert_message = span_alert("Please stand by for an important message from our head rat.<br>")
	custom_alert_message = null //Make it not obfuscate the content of the announcements
